#
# Makefile for the MPC85xxE PCI agent driver
#

obj-$(CONFIG_CARDNET) += pci_cardnet.o
obj-$(CONFIG_BOARDNET) += pci_boardnet.o

pci_cardnet-objs := pci_agent_lib.o pci_agent_drv.o
pci_boardnet-objs := pci_agent_lib.o  pci_agent_net.o
