#
# Makefile for the Freescale Ethernet controllers
#
EXTRA_CFLAGS           += -DVERSION=\"\"
#
#Include netcomm SW specific definitions
include $(srctree)/drivers/net/dpa/NetCommSw/ncsw_config.mk
#
obj-y		+= etc/
obj-y		+= integrations/P4080/
obj-y		+= Peripherals/FM/
obj-y		+= user/env/linux/kernel/2.6/
